name: flutterapp1
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  dio: ^1.0.13
  timeago: ^2.0.10
  scoped_model: ^1.0.1
  event_bus: ^1.0.1
  shimmer: ^0.0.6
  flutter_swiper : ^1.1.6
  webview_flutter: ^0.3.22+1

  provider: ^4.0.2
  fluro: ^1.5.1
  amap_location_fluttify: ^0.10.0+e74b91b

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/icon_home_tab.png
    - assets/images/icon_home_tab_pressed.png
    - assets/images/icon_popular_tab.png
    - assets/images/icon_popular_tab_pressed.png
    - assets/images/icon_movie_tab.png
    - assets/images/icon_movie_tab_pressed.png
    - assets/images/icon_mine_tab.png
    - assets/images/icon_mine_tab_pressed.png
    - assets/images/icon_empty.webp
    - assets/images/icon_load_error.png
    - assets/images/icon_placeholder.png
    - assets/images/icon_default_avatar.png
    - assets/images/icon_videodetail_num.png
    - assets/images/icon_videodetail_jishu.png
    - assets/images/icon_videodetail_name.png
    - assets/images/icon_videodetail_playlist.png
    - assets/images/icon_videodetail_director.png
    - assets/images/icon_videodetail_starring.png
    - assets/images/icon_videodetail_desc.png
    - assets/images/icon_rain.png
    - assets/images/icon_yin.png
    - assets/images/icon_sunny.png
    - assets/images/icon_snoy.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-1.4.otf
        # style: italic
    - family: FZLanTing
      fonts:
        - asset: assets/fonts/FZLanTingHeiS-DB1-GB-Regular.TTF
      # weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
